package sirius.utils;

public class REnum {

	public enum COLOR {BLUE, RED, YELLOW, BLACK, GREEN, DEEPPINK, DARKBLUE, CHOCOLATE, ALICEBLUE, AQUAMARINE, BROWN, BLUEVIOLET, CORAL,
		CORNFLOWERBLUE, CORNSILK, CYAN, DARKCYAN, DARKGOLDENROD, DARKGREY, DARKGREEN, DARKMAGENTA, DARKOLIVEGREEN, DARKORANGE, 
		DARKORCHID, DARKRED, DEEPSKYBLUE, GOLD, GOLDENROD, HONEYDEW, HOTPINK, INDIANRED, IVORY, KHAKI, LAVENDER,
		LEMONCHIFFON, MAGENTA, MAROON, MIDNIGHTBLUE, MINTCREAM, MISTYROSE, PEACHPUFF, SALOM, ROSYBROWN, SEAGREEN, SEASHELL,
		TOMATO, THISTLE, TURQUOISE, WHEAT, ORANGE};

	public enum LEGENDLOCATION {TOPLEFT, TOPRIGHT, TOPCENTER, BOTTOMLEFT};
}

